setup: revert slack-sdk upgrade
surface-security/django-notification-sender pull request #14
Opened 2023-02-16 11:00 UTC by gsilvapt

This is a lib and show have a wider range of dependency coverage. Solves #13.

2023-02-16 17:59 UTC, fopina requested changes

2023-02-17 10:05 UTC, gsilvapt commented on setup.cfg
> +    slack-sdk>=3.11.2
Maybe it's worth adding, as this is a bit volatile.

2023-02-17 10:05 UTC, gsilvapt commented on setup.cfg
> +    slack-sdk>=3.11.2
```suggestion
    slack-sdk>=3.11.2, <4
```

2023-02-17 10:34 UTC, fopina approved these changes

2023-02-17 10:37 UTC, merged